### Veamos el ejemplo en las slides

In [13]:
# detección de bordes:
import numpy as np
np.random.seed(0)
img = np.random.randint(0, 10, size=(5,5), dtype='l')
filtro = np.array([[1,0,-1],
                   [1,0,-1],
                   [1,0,-1]])
print(img)
print(filtro)

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]


### Multiplicación elemento a elemento y suma

In [20]:
np.sum(np.sum(img[0:3,0:3]*filtro))

5

In [ ]:
np.sum(np.sum(img[1:4,0:3]*filtro))

In [35]:
img = np.repeat([[10,10,10,0,0,0]], 6, axis=0)
print(img)

### Convolucionar la imagen entera y ver el resultado

In [41]:
# usamos scipy.signal.convolve2d
from scipy.signal import convolve2d
convolve2d(img,filtro,'valid')

array([[  0, -30, -30,   0],
       [  0, -30, -30,   0],
       [  0, -30, -30,   0],
       [  0, -30, -30,   0]])