### Ejemplo de max pool

In [6]:

import numpy as np

np.random.seed(0)
img = np.random.randint(0, 10, size=(4,4), dtype='l')

print(img)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]


In [7]:
np.max(img[0:2,0:2])

9

### Ejemplo de max pool en la imagen entera

In [8]:
salida = np.zeros((2,2))
for i in range(2):
  for j in range(2):
    salida[i,j] = np.max(img[2*i:2*i+2,2*j:2*j+2])

print(salida)

[[9. 5.]
 [8. 7.]]
